version: '1'
services:
  mongodb:
      image: mongo:6.0
      container_name: mongodb
      hostname: mongodb
      env_file:
        .env
      ports:
        - 27017:27017
      volumes:
        - ./algoritmosymazmorras